name: lighthouse

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install lighthouse
        run: sudo npm i -g lighthouse

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      # - name: Seed Test Data
      #   run: yarn init:seeds 2023-01-25 2023-02-27

      - name: Build
        run: yarn build

      - name: Run Server
        run: concurrently -k -s first -n "SERVER,LIGHTHOUSE" -c "magenta,blue" "yarn serve:test --silent" "wait-on tcp:3000 && lighthouse --chrome-flags='--headless' --output html --output-path ./report.html 'http://localhost:3000'"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: report${{ github.sha }}.html

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Lighthouse report for this PR is available [here](${{ github.event.repository.html_url }}/blob/gh-pages/report${{ github.sha }}.html)
