name: lighthouse

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install lighthouse
        run: sudo npm i -g lighthouse

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run Server
        run: >
          npx concurrently -k -s first -n "SERVER,LIGHTHOUSE" -c "blue,red" "yarn serve:test" \
          "wait-on tcp:3000 && lighthouse --chrome-flags='--headless' --output json --output-path ./report/top.json http://localhost:3000 && lighthouse --chrome-flags='--headless' --output json --output-path ./report/race-card.json http://localhost:3000/races/e42f0190-2d4c-4a9e-a1a0-5d025979ab95/race-card && lighthouse --chrome-flags='--headless' --output json --output-path ./report/odds1.json http://localhost:3000/races/e42f0190-2d4c-4a9e-a1a0-5d025979ab95/odds && lighthouse --chrome-flags='--headless' --output json --output-path ./report/odds2.json http://localhost:3000/races/ba77cb90-d030-43a8-9fec-1690a93f2be1/odds && lighthouse --chrome-flags='--headless' --output json --output-path ./report/result.json http://localhost:3000/races/e42f0190-2d4c-4a9e-a1a0-5d025979ab95/result"

      - name: Calc Total Score
        run: |
          node ./report/score.js > ./report/score.txt

      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            <details>
            <summary>Report</summary>
            Score:
            <pre>
            $(cat ./report/score.txt)
            </pre>
            </details>
